"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { ApolloWrapper } from "@/utils/apollo-wrapper";
import { Providers } from "@/utils/apollo-clients";
import { ApolloProvider } from "@apollo/client";

import { ApolloClient } from "@apollo/client";
import { InMemoryCache } from "@apollo/client";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const client = new ApolloClient({
  uri: "http://localhost:3000/api/graphql",
  cache: new InMemoryCache(),
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ApolloProvider client={client}>{children}</ApolloProvider>
      </body>
    </html>
  );
}
